name: Lambda Deploy - Simple Action Example

# Minimal example for teams who prefer direct action usage
# This is the simplest way to use the lambda-deploy action

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to AWS Lambda
        uses: YourOrg/devops-actions/.github/actions/lambda-deploy@lambda-deploy/v1.0.0
        with:
          aws-region: eu-west-1
          s3-bucket: ${{ vars.S3_BUCKET_NAME }}
          lambda-function-name: ${{ vars.LAMBDA_FUNCTION_NAME }}
          environment: dev
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}