# Lambda Deploy Action Configuration
# This is the default configuration file for the Lambda Deploy Action
# Copy this file to your repository root and customize as needed

project:
  name: "lambda-function"  # Will be overridden by LAMBDA_FUNCTION_NAME if provided
  runtime: "python"       # Options: python, node, bun
  source_dir: "src"       # Source code directory
  build_dir: "dist"       # Build output directory (optional)

environments:
  dev:
    enabled: true
    branch_pattern: "^(dev|develop|feature/.*)$"
  pre:
    enabled: true
    branch_pattern: "^(staging|pre|release/.*)$"
  prod:
    enabled: true
    branch_pattern: "^(main|master|production)$"

deployment:
  timeout: 300              # Deployment timeout in seconds
  memory_size: 128          # Lambda memory size in MB
  timeout_lambda: 30        # Lambda function timeout in seconds

# Build commands - specify custom commands for each phase
build:
  commands:
    install: "npm ci"           # Install dependencies
    lint: "npm run lint"        # Run linting (blocks deployment on errors)
    test: "npm test"            # Run tests (blocks deployment on failures)
    build: "npm run build"      # Build the project
  artifact:
    path: "lambda-function.zip" # Path where build command creates the artifact
    
# Quality checks configuration - enable/disable quality checks
quality_checks:
  enabled: true
  lint: true               # Enable linting (uses build.commands.lint if specified)
  test: true               # Enable testing (uses build.commands.test if specified)
  security: true           # Run security scanning

notifications:
  on_success: true
  on_failure: true
  # Configure webhook URLs via environment variables:
  # TEAMS_WEBHOOK_URL, SLACK_WEBHOOK_URL, WEBHOOK_URL

rollback:
  enabled: true
  auto_rollback: true      # Automatically rollback on deployment failure
  health_check_retries: 3
  health_check_delay: 10   # Seconds between health checks
